source 'http://rubygems.org'

gem 'jekyll-unified-codeblocks', git: "https://github.com/razvii22/jekyll-unified-codeblocks"

gem "jekyll", "3.10.0"
gem "jekyll-avatar", "0.8.0"
gem "jekyll-coffeescript", "1.2.2"
gem "jekyll-default-layout", "0.1.5"
gem "jekyll-feed", "0.17.0"
gem "jekyll-gist", "1.5.0"
gem "jekyll-github-metadata", "2.16.1"
gem "jekyll-include-cache", "0.2.1"
gem "jekyll-mentions", "1.6.0"
gem "jekyll-optional-front-matter", "0.3.2"
gem "jekyll-paginate", "1.1.0"
gem "jekyll-readme-index", "0.3.0"
gem "jekyll-redirect-from", "0.16.0"
gem "jekyll-relative-links", "0.6.1"
gem "jekyll-remote-theme", "0.4.3"
gem "jekyll-sass-converter", "1.5.2"
gem "jekyll-seo-tag", "2.8.0"
gem "jekyll-sitemap", "1.4.0"
gem "jekyll-titles-from-headings", "0.5.3"
gem "jemoji", "0.13.0"
gem "jekyll-gitlab-metadata"
gem "kramdown-parser-gfm"